version: '2'

services:
  de-final-prj:
    image: cr.yandex/crp1r8pht0n0gl25aug1/de-final-prj:latest
    ports:
      - 8998:8998
      - 8280:8280
      - 15432:5432
    volumes:
      - mylessons:/lessons
      - ./src/dags:/lessons/dags
      - ./src/data:/data

volumes:
  mylessons: